CREATE TABLE Client
(
    accountNumber                 VARCHAR(8),
    PRIMARY KEY (accountNumber),
    compName                      VARCHAR(131) NOT NULL,
    brandName                     VARCHAR(50) NULL,
    custTypeCode                  VARCHAR(3) NOT NULL,
    CVATNO                        VARCHAR(14) NULL,
    segmentGroupLPCode            VARCHAR(5) NULL,
    segmentGroupCustCode          VARCHAR(5) NULL,
    RNANumber                     VARCHAR(12) NULL,
    activityEndDate               VARCHAR(40) NULL,
    active                        VARCHAR(3) NOT NULL,
    cDateTime                     VARCHAR(40) NOT NULL,
    siretCode                     VARCHAR(14) NULL,
    usualName                     VARCHAR(131) NULL,
    phone                         VARCHAR(30) NULL,
    validPhone                    VARCHAR(1) NULL,
    secondPhone                   VARCHAR(30) NULL,
    validSecondPhone              VARCHAR(30) NULL,
    fax                           VARCHAR(30) NULL,
    validFax                      VARCHAR(1) NULL,
    email                         VARCHAR(255) NULL,
    validEmail                    VARCHAR(1) NULL,
    webSite1                      VARCHAR(255) NULL,
    webSite2                      VARCHAR(255) NULL,
    webSite3                      VARCHAR(255) NULL,
    webSite4                      VARCHAR(255) NULL,
    webSite5                      VARCHAR(255) NULL,
    add2                          VARCHAR(255) NULL,
    add3                          VARCHAR(255) NULL,
    add4                          VARCHAR(255) NULL,
    add5                          VARCHAR(255) NULL,
    add6                          VARCHAR(255) NULL,
    add7                          VARCHAR(255) NULL,
    name1                         VARCHAR(100) NULL,
    -- RELAI
    siren                         VARCHAR(9) NULL, -- from topic = siretCode substring(0,9)
    updateDate                    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id0', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id1', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id10', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id11', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id12', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id13', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id14', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id15', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id16', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id17', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id18', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id19', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id2', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id20', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id21', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id22', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id23', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id24', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id25', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id26', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id27', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id28', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id29', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id3', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id30', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id31', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id32', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id33', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id34', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id4', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id5', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id6', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id7', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id8', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');
INSERT INTO Client (accountNumber, compName, brandName, custTypeCode, CVATNO, segmentGroupLPCode, segmentGroupCustCode, RNANumber, activityEndDate, active, cDateTime, siretCode, usualName, phone, validPhone, secondPhone, validSecondPhone, fax, validFax, email, validEmail, webSite1, webSite2, webSite3, webSite4, webSite5, add2, add3, add4, add5, add6, add7, name1, siren) VALUES ('id9', 'compName', 'brandName', 'cus', 'CVATNO', 'segme', 'segme', 'RNANumber', 'activityEndDate', 'act', 'cDateTime', '00001111789', 'usualName', 'phone', '0', 'secondPhone', 'validSecondPhone', 'fax', '1', 'email', '1', 'webSite1', 'webSite2', 'webSite3', 'webSite4', 'webSite5', 'add2', 'add3', 'add4', 'add5', 'add6', 'add7', 'name1', '000011117');